### PR TITLE
Handle item.state == absent by deleting the config file

### LINKED ISSUE #33: Program configs with state==absent are not removed
Right now, the only check that is present is whether `item.state != 'absent'` and if it's the case, the configuration is added to `conf.d`.

This makes it impossible to remove a program once it has been added, by setting its state to 'absent' afterwards.

A simple command that deletes the files when `item.state == 'absent'` would remedy this.
Or is this like that by design?

### PR DESCRIPTION
**Pull request by overfl0**
Fixes: https://github.com/geerlingguy/ansible-role-supervisor/issues/33

Program configs marked as absent will be deleted.

### CODE REVIEW

**Comment by overfl0** [comment]
Is this PR okay or is there something that needs changes?

**Comment by overfl0** [comment]
Bumping this Pull Request to make StaleBot happy ¯\\\_(ツ)\_/¯

**Comment by overfl0** [comment]
Bumping this issue to make StaleBot happy ¯\\\_(ツ)\_/¯

**Comment by kissifrot** [comment]
Yes it would be a great addition, as marking an item as absent has no use without this.

**Comment by nathansalter** [comment]
Really not sure why this hasn't been merged yet, seems like a fairly useful addition to this package. @geerlingguy are you waiting on something more to be done here?

**Review by gbdlin — APPROVED** [review]

**Review by ivellios — APPROVED** [review]

**Comment by overfl0** [comment]
Oh, it's that time of the year again! 🥳 

Bumping this issue to make StaleBot happy ¯\\\_(ツ)\_/¯

**Comment by geerlingguy** [comment]
Just let it go stale enough times and eventually it makes it into 2.2.0 :)

**Comment by overfl0** [comment]
> Just let it go stale enough times and eventually it makes it into 2.2.0 :)

Obviously 😉 

I was considering telling you that "I have all my time to bump this PR" but was afraid that you'd take that as a challenge 😁
Thanks for merging it in!

**Pull request merged**
