### PR TITLE
Fix supervisorctl password according to Supervisor docs

### PR DESCRIPTION
**Pull request by JakubCzarniecki**
As per http://supervisord.org/configuration.html#supervisorctl-section-settings.

### CODE REVIEW

**Comment by geerlingguy** [comment]
I'm trying to remember context here, but was it SHA pre-3.0?

**Comment by JakubCzarniecki** [comment]
Could be, including this role with default settings creates broken configuration now with Supervisor 3.0+, so this PR aims to fix it.

**Comment by oldskool** [comment]
+1 for this fix (although if it breaks pre 3.0, there should be some kind of check for this)

**Comment by geerlingguy** [comment]
Well, I'm usually one for using Semver appropriately; I'll bump the major version of the role to indicate people should check into this change before blindly updating to the latest version :)

**Pull request merged**
